jobs:
  - id: create_file
    name: Create File Job
    plugin: binary
    params:
      command: bash
      args:
        - "-c"
        - '
          echo "Your shell is $SHELL $((RANDOM % 100))";
          mkdir /tmp/configs/;
          echo -e "Hello from %JOB_ID%!\nThis file was created in %JOB_NAME% job." > /tmp/configs/hello.txt;
          '

  - id: hello_from_container
    name: Container Job 💬
    params:
      message: "Hello from %JOB_NAME% container!"
      job_id: "%JOB_ID%"
      job_name: "%JOB_NAME%"
    container:
      image: alpine:latest
      command: |-
        sh -c '
          echo "WHO AM I? $(whoami)"
          echo ">>>" ${message}! "<<<" && env
          tree -a /app/configs
          cat /app/configs/hello.txt

          echo -e "\n\nHi from ${job_id}!\nThis file was created in ${job_name} job." >> /app/configs/hello.txt
          cat /app/configs/hello.txt
        '
      engine: podman
      privileged: true
      volumes:
        - /tmp/configs:/app/configs
    depends_on:
      - create_file

  - id: result_from_file
    name: Echo results using file
    plugin: echo
    input:
      message: "==================FROM FILE==================\n{file:/tmp/configs/hello.txt}"
    depends_on:
      - hello_from_container

  - id: result_from_result
    name: Echo results using result
    plugin: echo
    input:
      message: "==================FROM RESULT==================\n{result:hello_from_container}"
    depends_on:
      - hello_from_container
