jobs:
  - id: notification_on_failure
    name: Notification on Failure
    enabled: false
    plugin: notifier
    params:
      message: "Rclone isnt running"

  - id: exit_job
    name: Exit Job
    enabled: false
    plugin: exit
    params:
      code: 1

  - id: check_rclone_health
    name: Check Rclone Health
    plugin: binary
    schedule: "* * * * *"
    params:
      command: bash
      args:
        - "-c"
        - "
          pgrep rclone || (echo 'Rclone is not running' && exit 1)
          "
    on_failure:
      - notification_on_failure
      # you can send kill switch to exit taskcrafter
      # - exit_job
