jobs:
  - id: hello_from_container
    name: Hello from Container
    params:
      message: "Hello from container!"
    container:
      image: alpine:latest
      command: |-
        env
      engine: podman
#   - id: delayed_job_with_timeoutpo
#     name: Delayed Job with Timeout
#     plugin: delayed_echo
#     params:
#       delay: 15
#       message: "This job (%JOB_ID%) will timeout after %JOB_TIMEOUT% seconds even though the delayed echo should start in %JOB_PARAMS_DELAY%."
#     timeout: 3
#   - id: hello_interval
#     name: Hello World every 10 seconds
#     plugin: echo
#     schedule: "* * * * *"
#     params:
#       message: "Hello, World every 10 seconds!"
#   - id: hello
#     name: Hello World Job
#     plugin: echo
#     params:
#       message: "Hello, World!"
#     enabled: false
#   - id: deploy
#     name: Deploy Job
#     plugin: echo
#     params:
#       message: "Deploying the project..."
#     depends_on:
#       - build
#       - test
#   - id: test
#     name: Test Job
#     plugin: echo
#     params:
#       message: "Running tests..."
#     depends_on:
#       - build
#   - id: build
#     name: Build Job
#     plugin: exception
#     max_retries:
#       count: 3
#       interval: 90
#     params:
#       message: "Building the project..."
#     on_success:
#       - hello
# #
