jobs:
  - id: hello_multiple
    name: Hello Multiple
    plugin: echo
    params:
      message: "Hello from %JOB_ID%!"
      number: 42
      current_time: "%CURRENT_TIME%"

  - id: checking_params_from_previous
    name: Checking params from previous job
    plugin: echo
    input:
      message: "The number is: {result:hello_multiple:number}@{result:hello_multiple:current_time}"
    depends_on:
      - hello_multiple
