jobs:
  - id: hello
    name: Hello World Job
    plugin: echo
    params:
      message: "Hello, World!"
    on_success:
      - hello_2
      - hello_world_success

  - id: hello_2
    name: Hello with params
    plugin: echo
    # enabled: false
    input:
      message: "this is second hello what will execute on success"

  - id: hello_world_success
    enabled: false
    name: Hello world Success Job
    plugin: desktop-notifier
    params:
      message: "We succeeded!"

  # - id: hello_2
  #   name: Hello with params
  #   plugin: echo
  #   input:
  #     message: "Well this is {result:hello:foo} without {result:hello:message}"
  #   depends_on:
  #     - hello
