jobs:
  # - id: execute_binary
  #   name: Execute Binary
  #   plugin: binary
  #   enabled: true
  #   params:
  #     command: echo
  #     args:
  #       - "Hello from binary plugin."
  #     env:
  #       MY_ENV_VAR: "BATMAN(%JOB_ID%)!"
  # - id: delayed_job_with_timeout
  #   name: Delayed Job with Timeout
  #   plugin: delayed_echo
  #   params:
  #     delay: 15
  #     message: "This job (%JOB_ID%) will timeout after %JOB_TIMEOUT% seconds even though the delayed echo should start in %JOB_PARAMS_DELAY%."
  #   timeout: 3
  - id: just_throwing_exceptions
    name: Exception Thrower 🐧
    plugin: exception
    params:
      message: "Well, this isnt good, right?"
    # retries:
    #   count: 3
    #   interval: 5
  # - id: hello_interval
  #   name: Hello World every minute
  #   plugin: echo
  #   schedule: "* * * * *"
  #   params:
  #     message: "Hello, World every minute!"
  # - id: hello
  #   name: Hello World Job
  #   plugin: echo
  #   params:
  #     message: "Hello, World!"
  #   on_success:
  #     - hello_world_success

  - id: hello_world_success
    enabled: false
    name: Hello world Success Job
    plugin: desktop-notifier
    params:
      message: "We succeeded!"

  - id: hello_world_failure
    enabled: false
    name: Hello world Failure Job
    plugin: desktop-notifier
    params:
      message: "We failed!"
